### ISSUE TITLE
[Epic] Initial Environment Setup

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#1]
### User Story

As a user I would like to be able to login and view UBDC's data portal with the default functionality and some extensions to effectively curate and publish data to the public

### Acceptance Criteria

- [x] Install CKAN 2.9.7 with self registration - ensure user info is not exposed
- [x] Information manager can login and access a public and private view of datasets
- [x] Information manager can publish/edit data with corresponding metadata records
- [x] Information manager can define subsets of data, eg organisations, groups, tagging etc
- [x] Information manager can publish, unpublish and delete data
- [x] Information manager can restrict and or remove datafile access by end-users
- [x] Information manager can publish additional web content such as Ts & Cs, FAQs etc
- [x] The system is exposed to search engine crawlers
- [x] #6
- [ ] Information manager can configure DCAT to automatically harvest data/metadata from 3rd party repositorie
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] The system is cloud based, hosted on Datopian servers
- [x] The system provides robust security and data encryption features
- [ ] User info is not exposed
- [x] Customizable URLs and redirects to maintain reverse compatibility and integrate with other UBDC systems

### Tasks

- [x] #14
    - [x] Install the latest CKAN version ckan v2.9.7
    - [x] Use latest datapusher (0.0.18 - Python3)
    - [x] Use Solr 8.1.1 
    - [x] Configure to restrict access user info to the public
    - [x] Enable [ckanext-dataexplorer-react](https://github.com/datopian/ckanext-dataexplorer-react) 
- [ ] #2 
- [x] #3 
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #8 
- [x] #9 
- [x] #11 
- [ ] Prepare any required technical documentation

**Comment by ismail-shahzad** [comment]
We already have a repo for ubdc, I think this was created when it was being demoed to the client.
I will use this one instead creating everything from scratch.

https://github.com/datopian/dx-helm-ubdc-staging

**Comment by juanbrits** [comment]
Hey @MuhammadIsmailShahzad thank you for the heads up. 
Should I transfer the issues from this repo into https://github.com/datopian/dx-helm-ubdc-staging ?

**Comment by ismail-shahzad** [comment]
@juanbrits I think we can keep it here if we don't need to make it private and also if all the other issues are going to be here (so that they all are in same location).

**Comment by sagargg** [comment]
**DONE**
