### ISSUE TITLE
2.2 Detailed analytics reporting is available

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#11]
### User Story

A user would like to see detailed analytics such as users, downloads, views, etc

### Acceptance Criteria

- [ ] A user can see traffic on their Google Console

### Tasks

- [x] Install Google Analytics new version
- [x] Request GA code from client
- [x] Implement GA Code for staging
- [x] Implement GA Code for prod
- [x] Ask client to change our Google access to viewer once done

**Comment by sagargg** [comment]
@juanbrits  I have installed the GA extension in staging ENV. GA property is created via my personal account.  I sent you an invite to that GA account.  

For production, we need to ask the client to provide GA ID or Measurement ID created from their account.
cc @MuhammadIsmailShahzad

**Comment by sagargg** [comment]
@juanbrits  If you need instructions to share with clients, here you can find the documentation.
https://github.com/datopian/ckanext-googleanalytics/tree/UBDC-project#setup

**Comment by juanbrits** [comment]
Hi @sagargg not sure if we were supposed to set this up from scratch or if the client already has a GA account whose GA ID they can share with us. We will need to confirm this in the client kickoff.

**Comment by juanbrits** [comment]
GA ids received. 
Requested maintainer access, but will need to change this to viewer once project is done



![Image](https://user-images.githubusercontent.com/103997912/204264907-06e860e8-6cf4-48f4-a5e6-5a461af1b100.png)

**Comment by sagargg** [comment]
**DONE**
