### ISSUE TITLE
[Epic] Frontend

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#12]
### User Story

A branding manager at UBDC would like to explore a portal that is inline with UBDC branding guidelines.

### Acceptance criteria

- [ ] An information manager can approve or reject a resource submission
- [ ] The branding on the portal is in line with their branding guidelines

### Tasks

- [x] #15
- [x] #19
- [x] UBDC Basic Design Implementation 
- [ ] UBDC Final Design Implementation
- [ ] QA

**Comment by juanbrits** [comment]
@sagargg please note the signup for NewsLetter should point to this URL: https://ubdc.us8.list-manage.com/subscribe?u=1cd141f60212494c03348938f&id=b53d9f1297

**Comment by juanbrits** [comment]
@sagargg  on the preview resource file page - on other projects I have seen that there is some info on the number of columns and number of rows but I only see the number of rows on UBDC. Is this expected?



![Image](https://user-images.githubusercontent.com/103997912/207294474-813adb9b-a220-43b7-ae9c-23ce3d9b5b95.png)

**Comment by juanbrits** [comment]
@sagargg just some things I think we can look at fixing if they are quick and easy next week:

I noticed that the markdown format on an organization is not pulling through in the descriptions:
See images below, is this expected behaviour?



![Image](https://user-images.githubusercontent.com/103997912/207585115-0d9e56fd-12e1-453e-98a5-0efbbf380e7e.png)


![Image](https://user-images.githubusercontent.com/103997912/207585243-e709af38-34e0-40d7-89c9-e39a8175d95a.png)


Also I think perhaps if we center aligned the text and numbers, this section may look a bit better?

Please also confirm if the custom metadata fields that are appearing on staging, will only be released to production in early January? We should only be deploying the design work you implemented tomorrow.

**Comment by juanbrits** [comment]
![Image](https://user-images.githubusercontent.com/103997912/211490219-ce8d41aa-caed-45bc-8576-101cf942f789.png)

**Comment by sagargg** [comment]
> I noticed that the markdown format on an organization is not pulling through in the descriptions:
  
@juanbrits this is expected, the preview on the sidebar is normal and does not include markdown formatting. The "Readmore" link directs to the organizations about page.

**Comment by juanbrits** [comment]
Thanks @sagargg 

Did you also notice that the buttons on issues is a lot bigger than the buttons on the other tabs such as Groups and Showcases?



![Image](https://user-images.githubusercontent.com/103997912/212014117-f50e024e-fcae-4af4-85e1-6914b6746e00.png)

**Comment by SusanBot85** [comment]
Client sign-off has been received, and the Designs are implemented on production.

RESOLVED.
