### ISSUE TITLE
[Internal] Deploy All Environments

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#13]
### User Story
A dev user would like to be able to test features on a staging environment prior to deploying them to production to avoid any possible downtime as a result of the new feature. 

### Acceptance Criteria

- [x] Dev/Staging deployed and identical to production
- [x] Production environment deployed and identical to staging, except in data   ✅ **2023-02-08  it's already identical only some client feedback changes are not deployed on production but they can be deployed along as we do the improvement.**

### Tasks

- [x] Check if we are deploying production to the client's own domain url (might need some instructions for this)
- [x] Ensure the client's GA ID is configured in production 
- [x] Ensure the staging data is not exposed to crawlers
- [ ] #23
- [x] Ensure that no testing data, orgs or groups are deployed to production.
- [x] Ensure that the DataCite credentials deployed to production are still testing credentials for now

**Comment by juanbrits** [comment]
@MuhammadIsmailShahzad just a reminder that we need to request the production domain url config from the client.

**Comment by juanbrits** [comment]
@MuhammadIsmailShahzad just added a task to ensure no testing data from staging is deployed into production. This should include the integration testing data, as well as any other testing data, organizations or groups we've created. Is this possible?

**Comment by sagargg** [comment]
@SusanBot85  @MuhammadIsmailShahzad   I think we can move this to done and close as most of the tasks are done. 
For one remaining task we can track separately.

**Comment by sagargg** [comment]
Closing as **DONE**.
