### ISSUE TITLE
[Internal] Integration Testing

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#16]
### Job Story
When I do testing prior to production release, I would like to be able to run automated integration dependencies on some of the basic exercises to test dependencies that are not normally covered with unit testing

### Acceptance Criteria

- [x] I can run automated tests that can check basic functions such us
- [x] Creating a user, logging in, creating an org and dataset
- [ ] I can test the restrict public user access
- [ ] I can test the resource submission and approval process
- [ ] I can test the resource submission and rejection process
- [x] The testing methods can be applied to similar CI/CD pipelines

### Tasks

- [x] Investigate current tests in Cypress
- [x] Fix errors
- [x] Apply to UBDC CI/CD pipeline
- [x] make sure that there is no residual datasets if any test fail

**Comment by juanbrits** [comment]
Ismail Shahzad:

 i looked into cypress testing last night. Some of the tests i fixed. Some are failing. Need to fix those and setting them up in our CI/CD may consume time as i would need to check how they can be added to our google build.
I will continue today.

**Comment by ismail-shahzad** [comment]
This has been done.
Integration tests are added to staging and prod.
On prod we are not creating/adding new datasets and orgs and only checking for the API(s) as adding new datasets was interfering with datacite I believe cc @sagargg

**Comment by sagargg** [comment]
@MuhammadIsmailShahzad  Can we close this issue ? 
cc @SusanBot85

**Comment by SusanBot85** [comment]
Hi @sagargg seems there are still outstanding issues:

As per feedback from @MuhammadIsmailShahzad 
These two test cases are missing, I think

- I can test the resource submission and approval process
-  I can test the resource submission and rejection process
As we have just added general tests for now, not the specific ones for the approval process.

And @sagargg can you provide some feedback on this: on prod we are not creating/adding new datasets and orgs and only checking for the API(s) as adding new datasets was interfering with datacite

**Comment by sagargg** [comment]
@SusanBot85   I have minimal information on this as @MuhammadIsmailShahzad and @geoffrey13 worked on the implementation. 

Yes, we are ignoring any dataset create/update action tests cases on production cuz it is interfering with datacite.
