### ISSUE TITLE
[Internal] QA

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#17]
### Tasks

- [x] The CKAN classic view has been deployed to production and all normal functions are in working order
- [x] I can create an organisation
- [x] I can create a dataset
- [x] I can create a group
- [x] I can add a resource to an organisation 
- [x] I can add a resource to a group 
- [x] I can publish showcases
- [x] I can publish news/blogs
- [ ] I can approve and reject datasource submissions made by editors
- [ ] The UI design for the homepage has been implemented 
- [ ] All links are relevant and direct to the intended source
- [ ] I can add a resource with Geographical Data tags and other custom metadata fields
- [x] I can register as a user
- [x] I as a sysadmin can add a member to an organisation
- [x] I as an editor can upload resources
- [ ] A DOI is created
- [ ] The DOI in production has been updated to the production credentials

**Comment by juanbrits** [comment]
![image](https://user-images.githubusercontent.com/103997912/207669837-9a7f1cf5-9cad-4f05-a210-0fd12812a641.png)
![image](https://user-images.githubusercontent.com/103997912/207669892-f94317d6-47e1-4331-99b9-d7d3c740ae83.png)
![image](https://user-images.githubusercontent.com/103997912/207669986-0cb7e815-7873-405f-97e1-dcd6acfbad20.png)
![image](https://user-images.githubusercontent.com/103997912/207670704-7b0935d3-708f-4fb3-bf38-35ba015d2e48.png)
![image](https://user-images.githubusercontent.com/103997912/207670800-4e2116d3-d22a-4dc8-bc4a-7313a27791e2.png)
![image](https://user-images.githubusercontent.com/103997912/207670884-b3cf903d-953b-4a19-bfcb-573b16157c40.png)
![image](https://user-images.githubusercontent.com/103997912/207671079-16ee97ae-306c-45d7-aaa6-30bbcbc945fc.png)

**Comment by sagargg** [comment]
@SusanBot85  I'm unsure about any remaining unfinished tasks, but I think all the work has been completed and is functioning properly.
Only the custom metadata implementation changes are not deployed on production but deployed on staging env.
