### ISSUE TITLE
1.5 Custom Metadata Schema

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#2]
### User Story

An information manager would like to define a custom metadata schema applicable to subsets of datasets so that they are **(to be discussed with client).**

### Acceptance Criteria

- [ ] Custom metadata per data set type

### Tasks

- [x] Add scheming extension 
- [x] Client to provide more detail on what metadata they want to have in the dataset
- [x] Deploy on staging
- [x] Sign off and deploy on production ✅  2023-02-20

**Comment by sagargg** [comment]
@anuveyatsu  @juanbrits 
If clients want preset metadata, we need to discuss with them what metadata they want to have in the dataset. 
or If they want more dynamic metadata then they can use CKAN extra custom fields where publishers can add new metadata as a key-value pair.

**Comment by juanbrits** [comment]
Thanks @sagargg as I understand we are installing the generic schema for now.

**Comment by juanbrits** [comment]
@sagargg I've updated the task description with a task to discuss the metadata requirements with them. 
For now, please help me understand if we are installing the generic schema for now?

**Comment by sagargg** [comment]
@juanbrits  Scheming extension is already installed with generic CKAN metadata schemas.

**Comment by juanbrits** [comment]
@juanbrits to extract the required fields from the client kick off meeting.

**Comment by juanbrits** [comment]
Custom metadata that the client would like to see @sagargg 

- Dataset name and description
- Geographic Location

**Comment by juanbrits** [comment]
Example from Ismail: https://github.com/ckan/ckanext-spatial to add longitude and latitude. 

Montreal and Metropole.

**Comment by juanbrits** [comment]
Juan to follow up on how the UNDD team would like to see Geographic data on custom schema

**Comment by juanbrits** [comment]
Heather would like to add the following to the Geographic Metadata:

City
Countries
Ability to do multiple geo tags in the metadata 

@sagargg please confirm if all is in order?

**Comment by sagargg** [comment]
@juanbrits  I think these should be added as Vocab tags if a single dataset can have multiple cities or countries.  How many hours do we estimated for this? Asking because implement with the Vocab approach could take ~2 days.

**Comment by juanbrits** [comment]
We have time enough allocated to the requirement for you to continue. 
Please keep me updated. It might be good to prioritize the basic frontend implementation prior to starting this. Let me know your thoughts?

**Comment by juanbrits** [comment]
Feedback from Heather on Geographical Metadata: 

In terms of geographical metadata, it varies it might be UK, Scotland, Glasgow, Edinburgh etc so it will be a text field and we need to be able to list a number of cities sometimes as many as 15 cities

**Comment by juanbrits** [comment]
@sagargg further feedback from Heather: 

In terms of custom metadata, in the old CKAN we uploaded metadata records as separate files see http://ubdc.gla.ac.uk/dataset/zoopla-property-data Zoopla Property Metadata

I've attached an Excel file with the generic fields. Ideally, we would like scope within CKAN to add all of the custom metadata record within CKAN so it’s searchable.

Here is the excel sheet Heather referred to with the custom fields on Zoopla: https://docs.google.com/spreadsheets/d/19SJ4zEumulEhr7_QyjjkpqWbJNPC7ajb/edit?usp=sharing&ouid=100589035423206434326&rtpof=true&sd=true

**Comment by juanbrits** [comment]
Currently still work in progress. Plan to publish early Jan 2023.

**Comment by juanbrits** [comment]
Hi @sagargg 

Just a few changes I think we should make:

- [x] On manage package > metadata schema > Dataset Updating Frequency > Please change the placeholder to "e.g Monthly"
- [x] On manage package > metadata schema > Dataset Available > Please make Dataset Available selectable by a calendar as well, see Dataset Closed as example.

**Comment by sagargg** [comment]
Already **DONE** but yet to be deploy on production.

**Comment by sagargg** [comment]
Reopening with updated tasks.

**Comment by sagargg** [comment]
Deployed on production
