### ISSUE TITLE
Dataset Fields to include a counter to show total number of fields

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#22]
### User Story

As a user of the UBDC portal, I would like to see how many datafields are available in total on a dataset, so that I have a clear indication that there are more than just the 5 dataset fields that are shown.

### Acceptance criteria
- [ ] The number of dataset fields is clearly visible on the dataset fields metatdata

## Tasks
* [x] Implement dataset fields count on codebase
* [x] Deploy on staging env.
* [x] Get signed off from the client 
* [x] Deployed on production.  ✅  2023-02-20

**Comment by sagargg** [comment]
@juanbrits  This is done and deployed on staging. You can test it now.

**Comment by juanbrits** [comment]
Hello @sagargg 
This is great but I think we should also add the counter here too:

![image](https://user-images.githubusercontent.com/103997912/216250827-eafc52d9-8880-4c95-8268-903987515f82.png)

**Comment by juanbrits** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/103997912/216280986-86b26ef6-df8b-4244-9f9f-7940828088f1.png)

**Comment by sagargg** [comment]
@SusanBot85  This is done and deployed on staging, and also demoed to the client.  We can deploy it on production once we get greenlight from the client.

**Comment by sagargg** [comment]
@SusanBot85 I'm moving this to the client blocker cuz we need to ask the client if it is okay to deploy on production.

**Comment by sagargg** [comment]
Deployed on both staging and prod.
