### ISSUE TITLE
Ensure production data is exposed to crawlers

### ISSUE THREAD

**Issue by SusanBot85** [datopian/ubdc-data-catalogue#23]
Enable DCAT extension to ensure production data is exposed to crawlers on Google Dataset when the site is live and the data portal has production datasets.

## Acceptance

* [ ] DCAT extension has been enabled on prod with the structured_data plugin

## Tasks

* [ ] Enable DCAT extension
* [ ] Enable structured_data plugin
