### ISSUE TITLE
[Client Feedback] Add license as dropdown option in dataset custom metadata  

### ISSUE THREAD

**Issue by sagargg** [datopian/ubdc-data-catalogue#25]
The current process for adding licenses for datasets involves manual entry into a custom metadata field, however the client has requested to change this to a dropdown option similar to what is available in the default CKAN.

<img width="800" alt="Screenshot 2023-02-08 at 4 15 26 PM" src="https://user-images.githubusercontent.com/87696933/217504605-a962ff02-28ee-422e-885d-f0598c387a72.png">

replace to 
 
<img width="800" alt="Screenshot 2023-02-08 at 4 19 46 PM" src="https://user-images.githubusercontent.com/87696933/217505572-6f0bf21b-59ad-49df-becc-55ad67dea9ed.png">

## Acceptance Criteria 
* [ ] I can see the dropdown option is implemented on the license field while creating a new dataset. 

## Tasks 
* [x] Implement 
* [x] Deploy on staging and test
* [x] Get signoff from the client 
* [x ] Deploy on the production  ✅  2023-02-20

**Comment by sagargg** [comment]
@SusanBot85  Once we implement this we can ask the client if we can deploy this along with  #22 , #2.

**Comment by sagargg** [comment]
Deployed on both envrionment
