### ISSUE TITLE
Estimate grouping the  datasets.

### ISSUE THREAD

**Issue by sagargg** [datopian/ubdc-data-catalogue#27]
The client asked if it's possible to group datasets in CKAN other than using organizations or groups, as they are already being utilized as providers and research themes.

We have already shared that it can be done with two options and will require custom development (plus doesn't fall on the current contract scope)
* With the Vocab tags  approach 
*  With adding new groups in CKAN with scheming extension (need to confirm if it doable. )

## Acceptance Criteria
* [ ]  I have a solution option for grouping datasets in CKAN (excluding group and organization) and estimating for each.

## Tasks
* [x]  Analysis of the solution options 
* [x] Estimate each 
* [x] Share with the team. 
* [x] Send to client **✅ Estimate sent to the clent** 

### Option 1: Adding Vocab tags with the specified name  - **[Est. 11 hrs]**
This implementation works similarly to the default tags (or topic after we renamed), where a user can assign one or multiple tags to a dataset but it will be separated from default tags. 

1. Addition input field will be added in the dataset create a UI to allow users to add tags.  It will look similar to the category field given in the screenshot (_Category field title is just a placeholder we can renamed it with any group name_)
<img width="1083" alt="Screenshot 2023-02-10 at 12 52 33 PM" src="https://user-images.githubusercontent.com/87696933/218025351-1e7931ac-6f12-4f00-8d86-68d88e777335.png">
2. A new facet filter will be available in the sidebar of the search page. This will allow users to filter datasets based on the selected categories.
<img width="563" alt="Screenshot 2023-02-10 at 12 56 53 PM" src="https://user-images.githubusercontent.com/87696933/218026105-930c1b5e-8b12-4af2-8c24-e1fb4362dcd0.png">

### Option 2: Adding new metadata on the dataset level  - **[Est. 6 hrs ]**
eg. Category or Group (or any other specified name ).

This option will work similarly to the license metadata field, where a user can select a predefined option to assign to a dataset. Just as with licenses, only one group option can be selected per dataset and a facet filter based on the selected group will be available on the search page.

1.  User will see the new select input filed metadata eg. Category input field on Dataset create UI where users get a predefined category or group options. Similar to below  (Note if the client wants to add a new group, they have to request us.)
    <img width="891" alt="Screenshot 2023-02-10 at 12 19 03 PM" src="https://user-images.githubusercontent.com/87696933/218019778-c86f8c61-8d7c-43bb-9f14-88e0b1bb16ab.png">
2.  Only one group option can be selected per dataset.
4.  A new facet filter will be added to the sidebar of the search page. This will allow users to filter datasets based on the selected group.

### Option 3: Creating replicas of the Generic CKAN group. - [Est. No estimate/ not going to suggest]
Doable but quite complex since it is already renamed with Research Themes.  We shouldn't suggest that.
