### ISSUE TITLE
1.9 Publish additional web content

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#4]
### User Story

An information manager would like to publish additional content to the CKAN portal that serve to inform users about UBDC's goals, objectives and initiatives 

### Acceptance Criteria

- [x] A UBDC user can publish pages
- [x] A UBDC user can publish showcases

### Tasks

- [x] Add pages extension
- [x] Add showcases extension

**Comment by ismail-shahzad** [comment]
Enabled pages: `/pages` and `/blog` endpoints are accessible now.
Enabled showcase: showcases can be published now.

**Comment by juanbrits** [comment]
@MuhammadIsmailShahzad when I manage the test showcase, and try to add a description or even an image to the showcase, when I click on update showcase it returns an error 500 . 



![Image](https://user-images.githubusercontent.com/103997912/202992403-67da94d5-5d8c-44a7-872b-ad29e481b07a.png)

**Comment by ismail-shahzad** [comment]
Error Traceback

```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.9/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/srv/app/src/ckanext-showcase/ckanext/showcase/views.py", line 73, in post
    context = self._prepare()
TypeError: _prepare() missing 1 required positional argument: 'id'

```

**Comment by ismail-shahzad** [comment]
@juanbrits this is fixed now. Had to bump the showcase extension to a newer version.

**Comment by juanbrits** [comment]
Thank you @MuhammadIsmailShahzad all seems in order here.

**Comment by sagargg** [comment]
**DONE**
