### ISSUE TITLE
1.10 Exposed Metadata To Relevant Scrapers

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#5]
### User Story

A user at UBDC would like the metatdata of he portal to be exposed to relevant scrapers and crawlers

### Acceptance Criteria

- [ ] Metadate is indexed by Google Dataset Search

### Tasks

- [x] Install DCAT Extension
- [x] Configure to be indexed by Google Dataset Search
- [ ] Disable indexing in staging and dev environments once production is enabled

**Comment by sagargg** [comment]
@juanbrits 
DCAT and structured_data  plugins are enabled. The JSON-LD metadata is exposed for google dataset search indexing. However, it will take some time to be indexed.  

<img width="1505" alt="Screenshot 2022-11-17 at 4 46 02 PM" src="https://user-images.githubusercontent.com/87696933/202429250-f368da3a-7b91-4116-887e-e6e13db1c377.png">

Note: We should disable that later once we have production env.  Staging and dev datasets shouldn't be shown on dataset search engine
cc @MuhammadIsmailShahzad

**Comment by sagargg** [comment]
DONE. Implemented DCAT on staging. For production, we have a separate issues here
https://github.com/datopian/ubdc-data-catalogue-pm/issues/23
