### ISSUE TITLE
The system integrates with University of Glasgow's Datacite subscription

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#6]
### User Story

A UBDC user would like CKAN to integrate with their datacite subscription to generate DOIs for created records

### Acceptance criteria

- [ ] DOIs successfully being created

### Tasks

- [x] Install datacite extension
- [x] Request datacite subscription details from client
- [x] Configure datacite extension

**Comment by ismail-shahzad** [comment]
Are we referring to this extension https://github.com/NaturalHistoryMuseum/ckanext-doi ?

**Comment by juanbrits** [comment]
@MuhammadIsmailShahzad I believe we need to confirm this with @anuveyatsu ?

**Comment by sagargg** [comment]
Will sync with Dragan on this task as he has already worked on a similar issue.

**Comment by sagargg** [comment]
@juanbrits  I synced with @gavram. He provided the test account credentials and tested but unfortunately, I cannot make it work. Will investigate further.
This is the error i got. It may be because of misconfiguration of the environment variable or account. Basically, it is returning 404 when updating DOI metadata. 


```
https://mds.datacite.org/metadata
2022-11-16 12:47:00,181 ERROR [ckan.config.middleware.flask_app] Not found
Traceback (most recent call last):
  File "/Users/sagarg/.pyenv/versions/ckan-2.9/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sagarg/.pyenv/versions/ckan-2.9/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sagarg/.pyenv/versions/ckan-2.9/lib/python3.9/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/sagarg/.pyenv/versions/ckan-2.9/lib/python3.9/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/Users/sagarg/Documents/ckan/ckan/config/middleware/../../views/resource.py", line 272, in post
    get_action(u'package_update')(
  File "/Users/sagarg/Documents/ckan/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/Users/sagarg/Documents/ckan/ckan/logic/action/update.py", line 338, in package_update
    item.after_update(context, data)
  File "/Users/sagarg/Documents/ckanext/ckanext-doi/ckanext/doi/plugin.py", line 74, in after_update
    client.set_metadata(doi.identifier, xml_dict)
  File "/Users/sagarg/Documents/ckanext/ckanext-doi/ckanext/doi/lib/api.py", line 137, in set_metadata
    self.client.metadata_post(xml_doc)
  File "/Users/sagarg/Documents/ckanext/ckanext-doi/ckanext/doi/lib/datacite_local.py", line 145, in metadata_post
    raise DataCiteError.factory(resp.status_code, resp.text)
datacite.errors.DataCiteNotFoundError: Not found

```
From the investigation i found that extension is using this api to update the DOI metadata. 
https://support.datacite.org/docs/mds-api-guide

**Comment by juanbrits** [comment]
@sagargg please can you advise what the next steps here are please?

**Comment by sagargg** [comment]
@juanbrits  As I said already we need to investigate further. I will invest some time during my weekend to understand this issue. I hope we will find a way after that.

 Also, @gavram was saying that issue would be with our test account so he was suggesting to test with client credentials which might work. For that, we need to request the client to provide their credentials.

**Comment by juanbrits** [comment]
@sagargg please note that Heather has sent us credentials for DataCite. Please see email sent by her on 30 November.

**Comment by sagargg** [comment]
@juanbrits  DOI is installed in staging, it is now showing cite information on the dataset and also indexed in datacite repository as shown in the screenshot but links are not working, probably it is due to the test account. I don't have much knowledge of how DOI is supposed to work so please ask the client to test it and let us know what is not working. 

**CKAN Dataset**  
<img width="925" alt="Screenshot 2022-12-02 at 4 15 50 PM" src="https://user-images.githubusercontent.com/87696933/205272777-bd625f88-6fb3-4281-9f93-8849744b3225.png">

**On Datacite**
<img width="1512" alt="Screenshot 2022-12-02 at 4 17 42 PM" src="https://user-images.githubusercontent.com/87696933/205273157-cccd8d2a-ae0d-4e21-96e6-171aae140c86.png">

**Comment by juanbrits** [comment]
Hello all

I hope all is well... 

We have implemented the datacite testing credentials and as far as we can see everything is working. 
May we please ask that you cast an eye and confirm if everything looks in order on your end.

The following details have been supplied by our dev:

image.png
image.png

We have noted that the links are not working properly - could this be related to the testing credentials?

Look forward to hearing from you.

**Comment by juanbrits** [comment]
@sagargg please see feedback from client below: 

"I checked with a colleague and he thinks the urls are correct – he can see you’ve added a test record:

 

curl --user BL.GLASGOW:yamtssfa https://mds.test.datacite.org/metadata/10.5525/gu8fatrj

 

so the test one must have worked?  Are you having trouble creating the real DOIs?

 

thanks"

Could you please confirm if there is indeed still an issue? Did I perhaps miscommunicate something to the client?

**Comment by juanbrits** [comment]
@juanbrits Ask client to check the metadata that have been pushed from CKAN and confirm if this is valid?

**Comment by juanbrits** [comment]
@sagargg latest feedback from Heather on DOIs:

For minting DOIs we just need the fields as per the Zoopla xml file.

I've looked at https://mds.test.datacite.org/metadata/10.5525/gu8fatrj and it includes these fields but could we add in the version field as well please? e.g. <version>1.0</version> The datasets change a lot because of the new extracts created by the data scientists so we need to reflect this.

**Comment by juanbrits** [comment]
All work here is done and tested. However there is a dependency on an additional custom meta data field, this still needs to be added. We're working on this issue over the coming week to ensure that we can line up a full deployment here in Jan 2023.

**Comment by juanbrits** [comment]
@sagargg please double check that the DataCite credentials deployed to production remain the testing credentials for now? Until we've completed the custom metadata schema?

**Comment by juanbrits** [comment]
@sagargg please can you check that the additional custom metadata fields are also integrating with Glasgow's Datacite Subscription ?

**Comment by sagargg** [comment]
yes. It is working on staging. On production, it is yet to be tested there. 
For now, closing as **DONE**. We can create a separate issue for production later once we deployed custom metadata implementation there.
