### ISSUE TITLE
1.14 End-user can explore common format datasets inline within web interface (e.g. tabular, geospatial, JSON, XML)

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#8]
### User Story

A UBDC user would like to explore/preview common format datasets within the web interface

### Acceptance Criteria

- [x] A user can explore maps
- [x] A user can explore tables
- [x] A user can explore JSON

### Tasks

- [x] Install next gen data explorer extension with all available views

**Comment by ismail-shahzad** [comment]
Next Gen dataexplorer has been installed.
Need to confirm the above mentioned views.

**Comment by sagargg** [comment]
@MuhammadIsmailShahzad  We have a cors issue for JSON view. I guess we have to add the staging URL to the GCP bucket cors whitelist. 
<img width="1512" alt="Screenshot 2022-11-17 at 4 56 20 PM" src="https://user-images.githubusercontent.com/87696933/202431276-ebd8a0c9-dd97-411f-ae19-f66613802811.png">
cc @juanbrits

**Comment by ismail-shahzad** [comment]
@sagargg @juanbrits this is fixed
JSON view is working fine now
![image](https://user-images.githubusercontent.com/57398621/203364412-97c8f440-69ad-404a-87f2-11816581285e.png)

**Comment by sagargg** [comment]
**DONE**
