### ISSUE TITLE
1.15 End-user can login to propose feedback and comments on datasets

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#9]
## Acceptance Criteria 
* [ ] I can see issue extension is installed and functional in staging env.

## Tasks
* [x] Install Issue extension.
* [x] Disable email notifications for now. We can discuss it with the client if they want that.

**Comment by sagargg** [comment]
@juanbrits  installed the issue extension.
https://ckan.ubdc.staging.datopian.com/dataset/test-dataset/issues
cc @MuhammadIsmailShahzad

**Comment by juanbrits** [comment]
@sagargg I am unable to assign an issue to a user. Can you please have a look and advise?



![Image](https://user-images.githubusercontent.com/103997912/202993294-eb1fa2a2-9cfe-4a8f-bb63-6dbbbee0805e.png)

**Comment by sagargg** [comment]
@juanbrits  you need to provide the correct user name.

**Comment by sagargg** [comment]
try adding `ckan_admin `.

**Comment by juanbrits** [comment]
Thanks @sagargg that was a little confusing as I didn't get a prompt or anything. 

Is there not a dropdown that can appear? The dropdown should update with usernames as the user is typing so that they are prompted to select a user. 

Does this make sense?

**Comment by sagargg** [comment]
@juanbrits I will check if it has to autocomplete or user suggestions when the user starts typing.

**Comment by sagargg** [comment]
@juanbrits  This is fixed.
<img width="485" alt="Screenshot 2022-11-23 at 11 50 00 AM" src="https://user-images.githubusercontent.com/87696933/203481936-5ce9f8dc-cb35-4128-8478-8c3ffb1c6c66.png">

**Comment by juanbrits** [comment]
Thank you @sagargg all seems in order!

**Comment by sagargg** [comment]
**DONE**
